default_context:
  project_name: 'xxxten'
  project_slug: 'xxxten'
  domain_main: 'xxxten.com'
  domain_staging: 'stag.xxxten.com'
  docker_swarm_stack_name_main: 'xxxten-com'
  docker_swarm_stack_name_staging: 'stag-xxxten-com'
  secret_key: '1712f63d81c1b02791ea49919328f6bcce667761b837af910ad5b99dda71df23'
  first_superuser: 'louispuyo@yahoo.fr'
  first_superuser_password: 'a04b7c5da0e8773bf879e3625f3119dd35ade29cf45912acc0fc9547c1607323'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.xxxten.com, https://stag.xxxten.com, https://xxxten.com, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@xxxten.com'
  postgres_password: 'b7dc90610f283561d9c1461b917735a2a1f7d8317b2cf4e3cb1b7f574ba66364'
  pgadmin_default_user: 'louispuyo@yahoo.fr'
  pgadmin_default_user_password: 'a04b7c5da0e8773bf879e3625f3119dd35ade29cf45912acc0fc9547c1607323'
  traefik_constraint_tag: 'xxxten.com'
  traefik_constraint_tag_staging: 'stag.xxxten.com'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:a04b7c5da0e8773bf879e3625f3119dd35ade29cf45912acc0fc9547c1607323'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
